version: "3.5"

volumes:
  data-postgresql:
    driver: local
  data-directus:
    driver: local

services:
  directus:
    container_name: phailgorithm.text-spinner.directus
    restart: always
    image: directus/directus:${DIRECTUS_VERSION:-9.9.1}
    ports:
      - ${DIRECTUS_LISTEN:-8055}:8055
    volumes:
      - data-directus:/directus/uploads
    env_file:
      - ${DIRECTUS_ENV_FILE:-.directus.env}
    environment:
      KEY: ${DIRECTUS_ENV_KEY:-key}
      SECRET: ${DIRECTUS_ENV_SECRET:-secret}
      DB_CLIENT: pg
      DB_HOST: ${DIRECTUS_ENV_DB_HOST:-phailgorithm.text-spinner.postgresql}
      DB_PORT: ${DIRECTUS_ENV_DB_PORT:-5432}
      DB_DATABASE: ${DIRECTUS_ENV_DB_DATABASE:-postgres}
      DB_USER: ${DIRECTUS_ENV_DB_USER:-postgres}
      DB_PASSWORD: ${DIRECTUS_ENV_DB_PASSWORD:-postgres}
      CACHE_ENABLED: "false"
      PUBLIC_URL: ${DIRECTUS_BASE_URI:-http://localhost:8055}
      AUTH_PROVIDERS: ${DIRECTUS_AUTH_PROVIDERS:-}

  postgresql:
    image: postgres:13
    container_name: phailgorithm.text-spinner.postgresql
    restart: always
    shm_size: "2gb"
    volumes:
      - data-postgresql:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_LISTEN:-127.0.0.1:5432:5432}
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD:-trust}

  node:
    container_name: phailgorithm.text-spinner.node
    image: node:16
    restart: unless-stopped
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    working_dir: /app
    command: node index.js
    ports:
      - ${NODE_LISTEN:-127.0.0.1:3000:3000}
