openapi: 3.0.0

info:
  title: Text Spinner API
  description: This is a simple text spinner API
  version: 0.1.3

servers:
  - url: http://localhost:3000
    description: Local development environment server

  - url: https://spinner.phailgorithm.app
    description: Production environment server

components:
  securitySchemes:
    bearerToken:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /api/v1/spinners/{id}:
    get:
      security:
        - bearerToken: []
      summary: Returns a spinner text
      parameters:
        - name: id
          in: path
          required: true
          description: Unique id of the spinner.
          schema:
            type: string
      description: Returns a spinner text.
      responses:
        '200':
          description: A string of spinner text
          content:
            text/html:
              schema:
                type: string
        '403':
          description: Request is not authorized
        '404':
          description: A spinner with the specified id was not found.
        '422':
          description: Invalid request data format.
        '500':
          description: Internal Server Error
